# Generated by Django 4.1.7 on 2023-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2api',
            name='app_id',
            field=models.CharField(help_text='The application id of the client app registration that creates the JWT', max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oauth2api',
            name='aud',
            field=models.CharField(help_text='The audience to check for normally it would be the Application ID URI', max_length=512),
        ),
        migrations.AlterField(
            model_name='oauth2api',
            name='iss',
            field=models.CharField(help_text='The issuer normally https://sts.windows.net/{tenant id}/', max_length=512),
        ),
        migrations.AlterField(
            model_name='oauth2api',
            name='jwks_uri',
            field=models.CharField(help_text='The JWKS URI', max_length=512),
        ),
    ]